AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Static Website Hosting. Debugged the code and fixed errors all throughout the template.
Revision: 2
Date: 09/22/2026

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: MyPolicy
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${S3Bucket.Arn}/*"

Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: URL for website hosted on S3

  S3BucketSecureURL:
    Value: !Sub "https://${S3Bucket.DomainName}"
    Description: HTTPS S3 bucket endpoint